### ISSUE TITLE
Bodiam Castle issue tracking

### ISSUE THREAD

**Issue by TheRealPear** [Warzone/PublicMaps#91]
### Map Name

Bodiam Castle

### Bug Type

Other or unsure

### Description

This is only an issue tracker for [Bodiam Castle](https://github.com/Warzone/PublicMaps/tree/main/DTM/Standard/Bodiam%20Castle) as I have no other way to help me organize and document any changes. It will be edited with more issues as I gather feedback from players and then closed once I feel the map reaches maturity.

- [ ] Prevent spawn blocking
- [x] Make spawn islands bigger and move beds couple blocks away from the spawn exit
- [ ] Block infinite water source (may not be possible)
- [x] Arrows are removed upon death but not bows (both should be removed, regardless of tier)
- [x] No tool downgrading on death (not possible at the moment with PGM)
- [x] Wool should likely not be on item remove (allow other blocks to be dropped as well?)
- [x] The max entities on the spawners should be adjusted (team spawners)

#### Reserved for Bodiam Castle v1.1.0
- [x] Replace villagers with the new [interactive shops](https://github.com/PGMDev/PGM/pull/1038)
- [x] Update world border to account for monostable filter changes
- [ ] Add [enderchests](https://github.com/PGMDev/PGM/pull/1045) with items dropping upon permanent death

#### Reserved for Bodiam Castle v2.0.0

- [x] Redesign middle castle
- [x] Redesign diamond towers
- [x] Redesign spawn (more exits, etc.)
- [x] Fix islands to look more natural
- [x] Implement resource upgrades (including kits)
- [x] Implement throwable fireballs
- [x] Port interactive shops from v1.1.0
- [x] Port world border changes

**Comment by TheRealPear** [comment]
Closing this as Bodiam Castle 2.0.0 is very close to completion; will probably add it to the repository by next week.
